version: '3'

services:
  api:
    build:
      context: .
    ports:
      - "12000:12000"
    depends_on:
      - db
    networks:
      - networkName

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: pmoreno
      POSTGRES_PASSWORD: Psiquiatrico1
      POSTGRES_DB: tfg_pmoreno
    ports:
      - '5432:5432'
    networks:
      - networkName

  frontend:
    build:
      context: ../tfg_pwa
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      - networkName

networks:
  networkName:
