version: '3'

services:
  api:
    build:
      context: .
    ports:
      - "12000:12000"
    depends_on:
      - db
    networks:
      - networkName

  db:
    image: postgres
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DEFAULT_DB}
    ports:
      - "5432:5432"
    networks:
      - networkName

  frontend:
    build:
      context: ../tfg_pwa
      dockerfile: Dockerfile
    ports:
      - "11000:80"
    networks:
      - networkName

networks:
  networkName: