"""Change primary key answer

Revision ID: 86e0fc9589ad
Revises: 06f62f2881ea
Create Date: 2023-08-31 01:10:13.944104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "86e0fc9589ad"
down_revision = "06f62f2881ea"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "answer", "id_assignment", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "answer", "id_question_question_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "answer", "id_question_module_id", existing_type=sa.INTEGER(), nullable=False
    )

    op.create_primary_key(
        "pk_answer",
        "answer",
        ["id_assignment", "id_question_question_id", "id_question_module_id"],
    )
    op.drop_column("answer", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "answer", sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.drop_constraint("pk_answer", "answer", type_="primary")

    op.alter_column(
        "answer", "id_question_module_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "answer", "id_question_question_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "answer", "id_assignment", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
