"""Add questionnarie

Revision ID: 8a4c13155a0d
Revises: 2411b17be32e
Create Date: 2023-05-04 00:42:02.072128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8a4c13155a0d"
down_revision = "2411b17be32e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_answer_questionnaire_link",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("questionnaire_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["questionnaire_id"],
            ["questionnaire.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "questionnaire_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_answer_questionnaire_link")
    # ### end Alembic commands ###
