"""Add

Revision ID: da00aff8043f
Revises: b677e8d92013
Create Date: 2023-07-07 17:09:12.683217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "da00aff8043f"
down_revision = "b677e8d92013"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "question",
        sa.Column("parent_question_id_question", sa.Integer(), nullable=True),
    )
    op.add_column(
        "question", sa.Column("parent_question_id_module", sa.Integer(), nullable=True)
    )
    op.drop_constraint("question_id_id_module_fkey", "question", type_="foreignkey")
    op.create_foreign_key(
        None, "question", "module", ["parent_question_id_module"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "question", type_="foreignkey")
    op.create_foreign_key(
        "question_id_id_module_fkey",
        "question",
        "question",
        ["id", "id_module"],
        ["id", "id_module"],
    )
    op.drop_column("question", "parent_question_id_module")
    op.drop_column("question", "parent_question_id_question")
    # ### end Alembic commands ###
