"""Add

Revision ID: 66b1a5f8256e
Revises: da00aff8043f
Create Date: 2023-07-07 17:10:08.452243

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "66b1a5f8256e"
down_revision = "da00aff8043f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "question_parent_question_id_module_fkey", "question", type_="foreignkey"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "question_parent_question_id_module_fkey",
        "question",
        "module",
        ["parent_question_id_module"],
        ["id"],
    )
    # ### end Alembic commands ###
