"""Add user token

Revision ID: 9fd032eff6d8
Revises: aca0b09223d9
Create Date: 2023-05-07 12:42:45.241728

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "9fd032eff6d8"
down_revision = "aca0b09223d9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("token", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("user", "token")

    # ### end Alembic commands ###
