"""Add Role

Revision ID: 256a9719cdf4
Revises: e9c13e6c3ecd
Create Date: 2023-04-28 14:45:06.877166

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "256a9719cdf4"
down_revision = "e9c13e6c3ecd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    op.alter_column("user", "disabled", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "user", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "user", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "user", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column("user", "disabled", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_column("user", "role")
    # ### end Alembic commands ###
