"""Change fields type on patient

Revision ID: 44d48c0fa48a
Revises: 86e0fc9589ad
Create Date: 2023-08-31 19:24:56.508917

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "44d48c0fa48a"
down_revision = "86e0fc9589ad"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("patient", sa.Column("has_ci_barona", sa.Boolean(), nullable=True))
    op.add_column("patient", sa.Column("ci_barona", sa.Float(), nullable=True))

    # Change type of gender, education_level, region,zone to int
    op.alter_column(
        "patient",
        "education_level",
        existing_type=sa.String(),
        type_=sa.Integer(),
        nullable=True,  # Asegura que la columna admita valores nulos
        postgresql_using="NULLIF(education_level, '')::integer",
    )
    op.alter_column(
        "patient",
        "region",
        existing_type=sa.String(),
        type_=sa.Integer(),
        nullable=True,  # Asegura que la columna admita valores nulos
        postgresql_using="NULLIF(region, '')::integer",
    )
    op.alter_column(
        "patient",
        "zone",
        existing_type=sa.String(),
        type_=sa.Integer(),
        nullable=True,  # Asegura que la columna admita valores nulos
        postgresql_using="NULLIF(zone, '')::integer",
    )
    op.alter_column(
        "patient",
        "gender",
        existing_type=sa.String(),
        type_=sa.Integer(),
        nullable=True,  # Asegura que la columna admita valores nulos
        postgresql_using="NULLIF(gender, '')::integer",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "patient",
        "education_level",
        existing_type=sa.Integer(),
        type_=sa.String(),
        nullable=True,
        postgresql_using=None,  # Remove the postgresql_using clause
    )
    op.alter_column(
        "patient",
        "region",
        existing_type=sa.Integer(),
        type_=sa.String(),
        nullable=True,
        postgresql_using=None,
    )
    op.alter_column(
        "patient",
        "zone",
        existing_type=sa.Integer(),
        type_=sa.String(),
        nullable=True,
        postgresql_using=None,
    )
    op.alter_column(
        "patient",
        "gender",
        existing_type=sa.Integer(),
        type_=sa.String(),
        nullable=True,
        postgresql_using=None,
    )
    op.drop_column("patient", "ci_barona")
    op.drop_column("patient", "has_ci_barona")


# ### end Alembic commands ###
