"""Add delete on cascade for user

Revision ID: ff7027d66ab5
Revises: 057b6b5c4018
Create Date: 2023-08-12 18:33:44.020319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ff7027d66ab5"
down_revision = "057b6b5c4018"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "status", existing_type=sa.VARCHAR(), nullable=False)
    # Recreate the constraint with ON DELETE cascade all, delete orphan for the user table
    op.drop_constraint("patient_id_user_fkey", "patient", type_="foreignkey")
    op.create_foreign_key(
        "patient_id_user_fkey",
        "patient",
        "user",
        ["id_user"],
        ["email"],
        ondelete="CASCADE",
    )
    op.drop_constraint("doctor_id_user_fkey", "doctor", type_="foreignkey")
    op.create_foreign_key(
        "doctor_id_user_fkey",
        "doctor",
        "user",
        ["id_user"],
        ["email"],
        ondelete="CASCADE",
    )
    op.drop_constraint("admin_id_user_fkey", "admin", type_="foreignkey")
    op.create_foreign_key(
        "admin_id_user_fkey",
        "admin",
        "user",
        ["id_user"],
        ["email"],
        ondelete="CASCADE",
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "status", existing_type=sa.VARCHAR(), nullable=True)
    # Recreate the constraint with ON DELETE cascade all, delete orphan for the user table
    op.drop_constraint("patient_id_user_fkey", "patient", type_="foreignkey")
    op.create_foreign_key(
        "patient_id_user_fkey", "patient", "user", ["id_user"], ["email"]
    )
    op.drop_constraint("doctor_id_user_fkey", "doctor", type_="foreignkey")
    op.create_foreign_key(
        "doctor_id_user_fkey", "doctor", "user", ["id_user"], ["email"]
    )
    op.drop_constraint("admin_id_user_fkey", "admin", type_="foreignkey")
    op.create_foreign_key("admin_id_user_fkey", "admin", "user", ["id_user"], ["email"])
    # ### end Alembic commands ###
